# Generated by Django 6.0 on 2025-12-29 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('user', 'number', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('lecture', 'Лекционный курс'), ('practice', 'Практика'), ('coursework', 'Курсовая работа'), ('project', 'Проект'), ('exam', 'Экзамен'), ('other', 'Другое')], default='lecture', max_length=20)),
                ('expected_grade', models.CharField(blank=True, max_length=10, verbose_name='Ожидаемая оценка')),
                ('actual_grade', models.CharField(blank=True, max_length=10, verbose_name='Фактическая оценка')),
                ('for_diploma', models.BooleanField(default=False, verbose_name='В диплом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='grades.semester')),
            ],
        ),
    ]
