# Generated by Django 6.0 on 2026-01-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_discipline_actual_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='type',
        ),
        migrations.AddField(
            model_name='discipline',
            name='assessment_type',
            field=models.CharField(choices=[('exam', 'Экзамен'), ('pass', 'Зачёт'), ('pass_with_grade', 'Зачёт с оценкой'), ('interview', 'Итоговое собеседование')], default='exam', max_length=20, verbose_name='Вид контроля'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='actual_grade',
            field=models.CharField(blank=True, max_length=10, verbose_name='Фактическая оценка'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='expected_grade',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ожидаемая оценка'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='for_diploma',
            field=models.BooleanField(default=False, verbose_name='В диплом'),
        ),
    ]
